apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c5u6v1c66-go 
  janus-idp.io/tekton: c5u6v1c66-go
  backstage.io/kubernetes-id: c5u6v1c66-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c5u6v1c66-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  